apiVersion: v1
kind: ConfigMap
metadata:
  name: csgo-game-config
data:
  2v2.cfg: |
    // NPF #2017 - ESL - 14.01.2016
    ammo_grenade_limit_default 1
    ammo_grenade_limit_flashbang 2
    ammo_grenade_limit_total 4
    bot_quota "0"
    cash_player_bomb_defused 300
    cash_player_bomb_planted 300
    cash_player_damage_hostage -30
    cash_player_interact_with_hostage 150
    cash_player_killed_enemy_default 300
    cash_player_killed_enemy_factor 1
    cash_player_killed_hostage -1000
    cash_player_killed_teammate -300
    cash_player_rescued_hostage 1000
    cash_team_elimination_bomb_map 3250
    cash_team_hostage_alive 150
    cash_team_hostage_interaction 150
    cash_team_loser_bonus 1400
    cash_team_loser_bonus_consecutive_rounds 500
    cash_team_planted_bomb_but_defused 800
    cash_team_rescued_hostage 750
    cash_team_terrorist_win_bomb 3500
    cash_team_win_by_defusing_bomb 3500
    cash_team_win_by_hostage_rescue 3500
    cash_player_get_killed 0
    cash_player_respawn_amount 0
    cash_team_elimination_hostage_map_ct 2000
    cash_team_elimination_hostage_map_t 1000
    cash_team_win_by_time_running_out_bomb 3250
    cash_team_win_by_time_running_out_hostage 3250
    ff_damage_reduction_grenade 0.85
    ff_damage_reduction_bullets 0.33
    ff_damage_reduction_other 0.4
    ff_damage_reduction_grenade_self 1
    mp_afterroundmoney 0
    mp_autokick 0
    mp_autoteambalance 0
    mp_buytime 15
    mp_c4timer 40
    mp_death_drop_defuser 1
    mp_death_drop_grenade 2
    mp_death_drop_gun 1
    mp_defuser_allocation 0
    mp_do_warmup_period 1
    mp_forcecamera 1
    mp_force_pick_time 160
    mp_free_armor 0
    mp_freezetime 12
    mp_friendlyfire 1
    mp_halftime 1
    mp_halftime_duration 15
    mp_join_grace_time 30
    mp_limitteams 0
    mp_logdetail 3
    mp_match_can_clinch 1
    mp_match_end_restart 1
    mp_maxmoney 16000
    mp_maxrounds 30
    mp_molotovusedelay 0
    mp_playercashawards 1
    mp_playerid 0
    mp_playerid_delay 0.5
    mp_playerid_hold 0.25
    mp_round_restart_delay 5
    mp_roundtime 1.92
    mp_roundtime_defuse 1.92
    mp_solid_teammates 1
    mp_startmoney 800
    mp_teamcashawards 1
    mp_timelimit 0
    mp_tkpunish 0
    mp_warmuptime 1
    mp_weapons_allow_map_placed 1
    mp_weapons_allow_zeus 1
    mp_win_panel_display_time 15
    spec_freeze_time 2.0
    spec_freeze_panel_extended_time 0
    spec_freeze_time_lock 2
    spec_freeze_deathanim_time 0
    sv_accelerate 5.5
    sv_stopspeed 80
    sv_allow_votes 0
    sv_allow_wait_command 0
    sv_alltalk 0
    sv_alternateticks 0
    sv_cheats 0
    sv_clockcorrection_msecs 15
    sv_consistency 0
    sv_contact 0
    sv_damage_print_enable 0
    sv_dc_friends_reqd 0
    sv_deadtalk 0
    sv_forcepreload 0
    sv_friction 5.2
    sv_full_alltalk 0
    sv_gameinstructor_disable 1
    sv_ignoregrenaderadio 0
    sv_kick_players_with_cooldown 0
    sv_kick_ban_duration 0
    sv_competitive_minspec 1
    sv_competitive_official_5v5 1
    sv_pausable 1
    sv_pure 1
    sv_pure_kick_clients 1
    sv_pure_trace 0
    sv_spawn_afk_bomb_drop_time 30
    sv_steamgroup_exclusive 0
    sv_voiceenable 1
    sv_alltalk 0
    sv_auto_full_alltalk_during_warmup_half_end 0
    tv_enable 1
    tv_autorecord 1
    sv_coaching_enabled 1
  5v5.cfg: |
    // NPF #2017 - ESL - 14.01.2016
    ammo_grenade_limit_default 1
    ammo_grenade_limit_flashbang 2
    ammo_grenade_limit_total 4
    bot_quota "0"
    cash_player_bomb_defused 300
    cash_player_bomb_planted 300
    cash_player_damage_hostage -30
    cash_player_interact_with_hostage 150
    cash_player_killed_enemy_default 300
    cash_player_killed_enemy_factor 1
    cash_player_killed_hostage -1000
    cash_player_killed_teammate -300
    cash_player_rescued_hostage 1000
    cash_team_elimination_bomb_map 3250
    cash_team_hostage_alive 150
    cash_team_hostage_interaction 150
    cash_team_loser_bonus 1400
    cash_team_loser_bonus_consecutive_rounds 500
    cash_team_planted_bomb_but_defused 800
    cash_team_rescued_hostage 750
    cash_team_terrorist_win_bomb 3500
    cash_team_win_by_defusing_bomb 3500
    cash_team_win_by_hostage_rescue 3500
    cash_player_get_killed 0
    cash_player_respawn_amount 0
    cash_team_elimination_hostage_map_ct 2000
    cash_team_elimination_hostage_map_t 1000
    cash_team_win_by_time_running_out_bomb 3250
    cash_team_win_by_time_running_out_hostage 3250
    ff_damage_reduction_grenade 0.85
    ff_damage_reduction_bullets 0.33
    ff_damage_reduction_other 0.4
    ff_damage_reduction_grenade_self 1
    mp_afterroundmoney 0
    mp_autokick 0
    mp_autoteambalance 0
    mp_buytime 15
    mp_c4timer 40
    mp_death_drop_defuser 1
    mp_death_drop_grenade 2
    mp_death_drop_gun 1
    mp_defuser_allocation 0
    mp_do_warmup_period 1
    mp_forcecamera 1
    mp_force_pick_time 160
    mp_free_armor 0
    mp_freezetime 12
    mp_friendlyfire 1
    mp_halftime 1
    mp_halftime_duration 15
    mp_join_grace_time 30
    mp_limitteams 0
    mp_logdetail 3
    mp_match_can_clinch 1
    mp_match_end_restart 1
    mp_maxmoney 16000
    mp_maxrounds 30
    mp_molotovusedelay 0
    mp_playercashawards 1
    mp_playerid 0
    mp_playerid_delay 0.5
    mp_playerid_hold 0.25
    mp_round_restart_delay 5
    mp_roundtime 1.92
    mp_roundtime_defuse 1.92
    mp_solid_teammates 1
    mp_startmoney 800
    mp_teamcashawards 1
    mp_timelimit 0
    mp_tkpunish 0
    mp_warmuptime 1
    mp_weapons_allow_map_placed 1
    mp_weapons_allow_zeus 1
    mp_win_panel_display_time 15
    spec_freeze_time 2.0
    spec_freeze_panel_extended_time 0
    spec_freeze_time_lock 2
    spec_freeze_deathanim_time 0
    sv_accelerate 5.5
    sv_stopspeed 80
    sv_allow_votes 0
    sv_allow_wait_command 0
    sv_alltalk 0
    sv_alternateticks 0
    sv_cheats 0
    sv_clockcorrection_msecs 15
    sv_consistency 0
    sv_contact 0
    sv_damage_print_enable 0
    sv_dc_friends_reqd 0
    sv_deadtalk 0
    sv_forcepreload 0
    sv_friction 5.2
    sv_full_alltalk 0
    sv_gameinstructor_disable 1
    sv_ignoregrenaderadio 0
    sv_kick_players_with_cooldown 0
    sv_kick_ban_duration 0
    sv_competitive_minspec 1
    sv_competitive_official_5v5 1
    sv_pausable 1
    sv_pure 1
    sv_pure_kick_clients 1
    sv_pure_trace 0
    sv_spawn_afk_bomb_drop_time 30
    sv_steamgroup_exclusive 0
    sv_voiceenable 1
    sv_alltalk 0
    sv_auto_full_alltalk_during_warmup_half_end 0
    tv_enable 1
    tv_autorecord 1
    sv_coaching_enabled 1
